/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package bookmarks.model

import spock.lang.Specification

class BookmarkTest extends Specification {
    def "bookmark is cool"() {
        setup:
        def bookmark = new Bookmark()
        bookmark.name = "google"
        bookmark.url = "https://www.google.fr"

        when:
        def result = bookmark.name

        then:
        result != null && "google".equals(bookmark.name)
    }
}
