/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.drivet;

import java.net.UnknownHostException;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // MongoClient mongoClient = new MongoClient(new
        // MongoClientURI("mongodb://localhost:27017"));
        MongoClient mongoClient;
        try {
            mongoClient = new MongoClient();

            DB database = mongoClient.getDB("Bookmarksdb");

            DBCollection collection = database.getCollection("bookmarks");

            DBObject query = new BasicDBObject("name", "hotmail");
            DBCursor cursor = collection.find(query);

            System.out.println(cursor.one().get("url"));
            mongoClient.close();
        } catch (UnknownHostException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
